name: Rust

on:
  push:
    tags:
      - "*"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Install cargo components
      run: |
        cargo install cargo-generate-rpm

    - name: Build
      id: build
      run: |
        cargo build -r --verbose
        echo "tag=$(git tag)"


    - name: Build rpm package
      run: cargo generate-rpm

    - name: Upload rpm
      uses: actions/upload-artifact@v4
      with:
        path: target/generate-rpm/*.rpm
        name: sbs-fedora

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: target/generate-rpm/*.rpm
        tag_name: ${{ steps.build.outputs.tag }}
        name: ${{ steps.build.outputs.tag }}
        draft: false
        prerelease: false